name: PR Build

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    env:
      CARGO: cargo

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-unknown-linux-gnu

      - name: Build
        run: ${{ env.CARGO }} build --release --locked --target x86_64-unknown-linux-gnu

      - name: Create archive
        run: cargo xtask create-archive
        env:
          STAGING: scarb-pr-${{ github.event.pull_request.number }}-x86_64-unknown-linux-gnu
          TARGET: x86_64-unknown-linux-gnu

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-x86_64-unknown-linux-gnu
          path: scarb-pr-${{ github.event.pull_request.number }}-x86_64-unknown-linux-gnu.*
          retention-days: 14